apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: app-image:latest
          imagePullPolicy: Never
          command: ["bundle", "exec", "rails", "db:setup", "db:from_fixtures"]
          env:
            - name: PSQL_DEV_HOST
              value: postgres
            - name: PSQL_TEST_HOST
              value: postgres
            - name: PSQL_DEV_USERNAME
              value: postgres
            - name: PSQL_DEV_PASSWORD
              value: password
            - name: PSQL_TEST_USERNAME
              value: postgres
            - name: PSQL_TEST_PASSWORD
              value: password
            - name: REDIS_URL
              value: redis://redis:6379/1
      restartPolicy: Never
