AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'

Documentation:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/HeredocIndentation:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Layout/SpaceInLambdaLiteral:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false
