AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
   - "bin/*"
   - "db/schema.rb"
   - "vendor/bundle/**/*"

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/HeredocIndentation:
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*.rb"

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Layout/SpaceInLambdaLiteral:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*.rb"

Metrics/AbcSize:
  Exclude:
    - "spec/**/*.rb"

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "spec/**/*.rb"

Metrics/MethodLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*.rb"

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/IfUnlessModifier:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false
