services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  migrate:
    image: app-image
    command: bundle exec rails db:setup db:from_fixtures
    environment:
      PSQL_DEV_HOST: postgres
      PSQL_TEST_HOST: postgres
      PSQL_DEV_USERNAME: ${POSTGRES_USER}
      PSQL_DEV_PASSWORD: ${POSTGRES_PASSWORD}
      PSQL_TEST_USERNAME: ${POSTGRES_USER}
      PSQL_TEST_PASSWORD: ${POSTGRES_PASSWORD}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  app:
    image: app-image
    command: bundle exec rails s -b 0.0.0.0
    environment:
      PSQL_DEV_HOST: postgres
      PSQL_TEST_HOST: postgres
      PSQL_DEV_USERNAME: ${POSTGRES_USER}
      PSQL_DEV_PASSWORD: ${POSTGRES_PASSWORD}
      PSQL_TEST_USERNAME: ${POSTGRES_USER}
      PSQL_TEST_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_URL: redis://redis:6379/1
    ports:
      - '3000:3000'
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  sidekiq:
    image: app-image
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379/1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  postgres_data: