services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'

  app:
    build: .
    image: app-image
    command: bundle exec rails s -b 0.0.0.0
    environment:
      PSQL_DEV_HOST: postgres
      PSQL_TEST_HOST: postgres
      PSQL_DEV_USERNAME: ${POSTGRES_USER}
      PSQL_DEV_PASSWORD: ${POSTGRES_PASSWORD}
      PSQL_TEST_USERNAME: ${POSTGRES_USER}
      PSQL_TEST_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_URL: redis://redis:6379/1
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis

  sidekiq:
    image: app-image
    command: bundle exec sidekiq
    restart: always
    environment:
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - redis
      - app

volumes:
  postgres_data:
