development:
  adapter: redis
  url: <%= OstConfig.redis_url %>
  channel_prefix: open_split_time_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= OstConfig.redis_url %>
  channel_prefix: open_split_time_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
