local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  # access_key_id and secret_access_key are read and set directly from the
  # Rails.credentials encrypted file by the aws-sdk-rails gem.
  # https://github.com/aws/aws-sdk-rails#rails-52-encrypted-credentials
  service: S3
  region: <%= ::OstConfig.aws_region %>
  bucket: <%= ::OstConfig.aws_s3_bucket %>
