apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: app-image:latest
          imagePullPolicy: Never
          command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
          env:
            - name: PSQL_DEV_HOST
              value: postgres
            - name: PSQL_TEST_HOST
              value: postgres
            - name: PSQL_DEV_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_USER
            - name: PSQL_DEV_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PASSWORD
            - name: PSQL_TEST_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_USER
            - name: PSQL_TEST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PASSWORD
            - name: REDIS_URL
              value: redis://redis:6379/1
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
